source 'https://rubygems.org'

ruby '3.1.2'

gem 'middleman', '~> 4.4'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'webrick'
gem 'httparty'
gem 'activesupport', '~> 6.1.6.1'
gem 'cloudinary'
gem 'aws-sdk-s3'
gem 'aws-sdk-cloudfront'
gem 'json'
gem 'dotenv'
gem 'aws-sdk-mediaconvert'
